tutorial: nuttx: update micro-ROS over 6lowpan
micro-ROS/micro-ROS.github.io pull request #213
Opened 2020-09-09 07:08 UTC by amx-piap

2020-09-09 08:39 UTC, FranFin requested changes

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +First the PmodRF2 need to be connected to the Olimex board as desribed below:
```suggestion
First the PmodRF2 needs to be connected to the Olimex board as desribed below:
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +The micro-ROS build system will be use in order to create and flash the
```suggestion
The micro-ROS build system will be used in order to create and flash the
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Instructions are available at the following link: [Micro-ROS build system](https://github.com/micro-ROS/micro-ros-build/blob/dashing/micro_ros_setup/README.md).
```suggestion
Instructions are available at the following link: [Micro-ROS build system](https://github.com/micro-ROS/micro_ros_setup/blob/dashing/micro_ros_setup/README.md).
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Due to the build system being a work in progress, some of files have to be
```suggestion
Due to the build system being a work in progress, some of the files have to be
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Also the micro-XRCE-DDS needs to be to be change to the version 1.2.5 in the docker:
```suggestion
Also the Micro-XRCE-DDS library needs to be changed to the version 1.2.5 in the docker:
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Once the modifications done, the binary can be compiled [as explained here](https://github.com/micro-ROS/micro_ros_setup/blob/dashing/micro_ros_setup/README.md)
```suggestion
Once the above modifications are done, the binary can be compiled [as explained here](https://github.com/micro-ROS/micro_ros_setup/blob/dashing/micro_ros_setup/README.md)
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +The Linux machine is where is going to run the agent.
```suggestion
The Linux machine is where the agent is going to be run.
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +In order to setup the wireless, some settings have to be set as follow:
```suggestion
In order to setup the wireless transport, some settings have to be set as follows:
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Once hte setup done, the docker may be run:
```suggestion
Once the setup is done, the docker may be run:
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +- Olimex-STM32-E407 board must be switched on and a connection to the NSH
```suggestion
- The Olimex-STM32-E407 board must be switched on and a connection to the NSH
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> + - Then the publisher can executed as follow. Note that the ipv6 address (fe80::bc81:c3b9:5c14:1ab) is the
```suggestion
 - Then the publisher can be executed as follow. Note that the IPv6 address (fe80::bc81:c3b9:5c14:1ab) is the
```

2020-09-09 08:39 UTC, FranFin commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +   ipv6 address of the Linux lowpan0 interface.
```suggestion
   IPv6 address of the Linux lowpan0 interface.
```

2020-09-10 04:30 UTC, walkiry approved these changes

2020-09-10 04:36 UTC, walkiry commented on _docs/tutorials/advanced/nuttx/6lowpan/index.md
> +Instructions are available at the following link: [Micro-ROS build system](https://github.com/micro-ROS/micro-ros-build/blob/dashing/micro_ros_setup/README.md).
Interesting, both links works for some reason.

2020-10-29 14:05 UTC, closed without merging