Changed occurrences of micro-ros-build into micro_ros_setup.
micro-ROS/micro-ROS.github.io pull request #214
Opened 2020-09-09 08:04 UTC by FranFin

2020-09-09 08:18 UTC, pablogs9 requested changes

2020-09-09 08:18 UTC, pablogs9 commented on _docs/overview/docker_ci_status/index.md
> +|[micro-ROS-setup](https://github.com/micro-ROS/micro_ros_setup)| Micro-ROS tool to build and flash Micro-ROS to every supported platform.|[![GitHub Actions status](https://github.com/micro-ROS/micro
```suggestion
|[micro_ros_setup](https://github.com/micro-ROS/micro_ros_setup)| Micro-ROS tool to build and flash Micro-ROS to every supported platform.|[![GitHub Actions status](https://github.com/micro-ROS/micro_ros_setup/workflows/CI/badge.svg)](https://github.com/micro-ROS/micro_ros_setup/actions)
```

2020-09-09 09:16 UTC, pablogs9 approved these changes

2020-09-09 09:17 UTC, pablogs9 commented
@jamoralp  merge if you approve

2020-09-18 07:16 UTC, jamoralp approved these changes

2020-09-18 07:23 UTC, merged