concept: benchmarking: introducing results
micro-ROS/micro-ROS.github.io pull request #229
Opened 2020-10-29 13:57 UTC by amx-piap

2020-11-11 14:18 UTC, ralph-lange requested changes

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +The low-level RTOS was instrumented in specific way that provide different categories of benchmarking results (memory, execution, etc...). The gathered data is following the [Common Trace Format](htt
```suggestion
The low-level RTOS was instrumented in specific way that provide different categories of benchmarking results (memory, execution, etc...). The gathered data is following the [Common Trace Format](https://diamon.org/ctf/). The raw trace is later processed using the [Babeltrace API](https://babeltrace.org/) trace manipulation toolkit. The data interpretation is up to the user.
```

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +More information about benchmarks results and methodologies are dealt with within the following document (TODO link to the deliverable).
Fix this ToDo or omit the whole sentence for now.

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +The results, on which the interpretation are done, are available in the [benchmarking_results](https://github.com/micro-ROS/benchmarking-results/tree/master/aug2020) repository.
Please link https://github.com/micro-ROS/benchmarking on the concept page similar as you link the https://github.com/micro-ROS/benchmarking-results repo here.

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +The results, on which the interpretation are done, are available in the [benchmarking_results](https://github.com/micro-ROS/benchmarking-results/tree/master/aug2020) repository.
Furthermore, can you write some sentences on the applications (its characteristic) that you used here? As far as I understood, there is not predefined set of benchmark apps in https://github.com/micro-ROS/benchmarking/, or?

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +
Please also describe the hardware and RTOS (here NuttX) setup used in your experiments.

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +## Function execution usage
I propose to call this _function invocations_ or _function call statistics_.

2020-11-11 14:18 UTC, ralph-lange commented on _docs/concepts/benchmarking/results/index.md
> +The medium has a high impact on the selection of the communication medium. This high throughput of a communication medium is coming at a price:  power consumption. The Ethernet provided a hight throu
```suggestion
The medium has a high impact on the selection of the communication medium. This high throughput of a communication medium is coming at a price:  power consumption. Ethernet provides a high throughput, but at the price of a higher power consumption. Serial provides a low bitrate with the advantage to it consumes a lot less energy.
```

2020-11-16 05:44 UTC, amx-piap commented
@ralph-lange thank you for your time to review. I agree with our changes and I am proceeding with the changes  requested

2020-11-19 13:57 UTC, FranFin requested changes

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Below the data processing described. From the serialised binary CTF data to the output from the Babeltrace API:
```suggestion
Below the data processing is described, from the serialized binary CTF data to the output from the Babeltrace API:
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Following is the execution benchmarking
```suggestion
Below we report the execution benchmarking
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +According to the results taken above, the software is running a deterministic way. Indeed, by looking closer, it is noticeable that the running sequence is the same.
```suggestion
According to the results reported above, the software is running in a deterministic way. Indeed, by looking closer, it is noticeable that the running sequence is the same.
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Additionally, timing deltas between correlated events have a really low variation when switch (consecutive thread_suspend/thread_resume).
```suggestion
Additionally, timing deltas between correlated events have a really low variation when switching between events (consecutive thread_suspend/thread_resume).
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Moreover, the scheduler performs fast context switches, on average the are around 10 microseconds.
```suggestion
Moreover, the scheduler performs fast context switches, which on average take around 10 microseconds.
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Following is depicted the execution benchmarking. The amount of time spend on the CPU split into two parts (I/O operations, Subscriber operations):
```suggestion
Below we report the execution benchmarking. The amount of time spent on the CPU is split into two parts (I/O operations and Subscriber operations):
```

I also want to mention that the same sentence (`Following is depicted the execution benchmarking`) appears at line 67. Possibly, one of the two is misplaced.

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Below are depicted the function calls count per each communication medium:
```suggestion
Below we report the function calls count per each communication medium:
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Below is the representation of the static memory analysis:
```suggestion
Below we provide the results for the static memory analysis:
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +The 6LoWPAN is the medium taking the most of the static memory as this protocol is running on top of IP version 6.
```suggestion
The 6LoWPAN is the medium consuming most of the static memory as this protocol is running on top of IP version 6.
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +Independently on the communication mediums, blocks allocated are not huge and not numerous.
```suggestion
Independent of the communication medium used, the blocks allocated are not too big nor too many.
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +The power consumption categorised by communication medium below:
```suggestion
Below, you can find the power consumption categorized by communication medium:

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +The medium has a high impact on the selection of the communication medium. This high throughput of a communication medium is coming at a price:  power consumption. The Ethernet provides a high throug
```suggestion
The communication medium has a high impact on the throughput that can be achieved, which in turn has an impact on power consumption. The Ethernet provides a high throughput, but at the price of higher power consumption while Serial transport provides a low bitrate with the advantage to consuming a lot less energy.
```

2020-11-19 13:57 UTC, FranFin commented on _docs/concepts/benchmarking/results/index.md
> +The graphic below is showing the total number dynamic allocations. Each bin is split into group of chunk memory blocks. For instance a block with the legend colored dark green represents all block th
I think this paragraph is a little bit confused. Also, by looking at the graph I'm not sure that the dark green block corresponds to the numbers that are given in this sentence. Could you try to rephrase it?

2020-11-20 06:52 UTC, amx-piap commented on _docs/concepts/benchmarking/results/index.md
> +The power consumption categorised by communication medium below:
Thank you for your time @FranFin,
Usually i try to use the passive voice when writing document and avoid using pronominals.
Also regarding the "categorized/categorised" I was told (by your company) that we are using British English in our documents, that's why usually 'Z' are 'S'

2020-11-20 09:10 UTC, tkolcon approved these changes
Approved.

2020-11-20 12:13 UTC, FranFin approved these changes

2020-11-23 14:44 UTC, ralph-lange approved these changes

2020-11-24 06:20 UTC, merged