New features list.
micro-ROS/micro-ROS.github.io pull request #230
Opened 2020-11-04 15:10 UTC by ralph-lange

2020-11-04 15:11 UTC, ralph-lange commented
@FranFin, @pablogs9, I completed the list of features from the virtual workshop. I also made a proposal how to group them and how to visualize the grouping (by vertical headlines).

2020-11-04 15:14 UTC, ralph-lange commented
However, I think that the list is too long. I propose to reduce it to seven items by combining always two features, except for 'permissive license' and 'seamless integration with ROS 2' as follows:

1. Microcontroller-optimized client API supporting all major ROS concepts
1. Seamless integration with ROS 2
1. Multi-RTOS support with generic build system
1. Extremely resource-constrained but flexible middleware
1. Permissive license
1. Vibrant community and ecosystem
1. Long-term maintainability and interoperability

What do you think, @FranFin, @pablogs9?

2020-11-05 11:12 UTC, jamoralp commented
It seems that some links are broken here, specifically all related to `ros2/tf2_filter` repository, as depicted from the failed CI execution.

2020-11-05 11:15 UTC, jamoralp commented on _docs/overview/features/index.md
> +
I would add here also some information about SOSS, since it's the tool used for communicating ROS2 with FIWARE, and also with any other supported system: https://soss.docs.eprosima.com/en/latest/

2020-11-06 11:22 UTC, ralph-lange commented
> 
> 
> It seems that some links are broken here, specifically all related to `ros2/tf2_filter` repository, as depicted from the failed CI execution.

This was caused by moving the geometry2 repo is not related to this PR. I just fixed it in https://github.com/micro-ROS/micro-ROS.github.io/commit/0ef39a5a44ed83dcb6fa94784a2943311cf57a93 and will rebase this PR.

2020-11-06 11:39 UTC, ralph-lange commented on _docs/overview/features/index.md
> +
@jamoralp, are you fine with the explanation on SOSS in https://github.com/micro-ROS/micro-ROS.github.io/pull/230/commits/52a4aeea22777a599f5c5e519f3ad79bec36c586 ?

2020-11-09 10:33 UTC, ralph-lange commented
@jamoralp, @FranFin: This is how a version with just seven features could look like.

2020-11-09 10:40 UTC, ralph-lange commented on _docs/overview/features/index.md
> +The combination rcl+rclc is optimized for MCUs. After an initialization phase, it can be used without any dynamic memory allocations. The rclc package provides advanced execution mechanisms allowing
@pablogs9, @FranFin, what about the micro_ros_arduino API? Should we name it already as an alternative to rcl+rclc (and omit rclcpp completely)?

2020-11-10 06:31 UTC, jamoralp commented on _docs/overview/features/index.md
> +The combination rcl+rclc is optimized for MCUs. After an initialization phase, it can be used without any dynamic memory allocations. The rclc package provides advanced execution mechanisms allowing
I would omit rclcpp since we are not really giving support to it. In slides and presentations we just mention `rclcpp` to say that it is not fully compliant with micro-ROS. Regarding the `micro_ros_arduino`, for me it makes more sense to mention it within the `supported RTOSes` section, although it is not really an RTOS, but a library; anyway, users would still write on `rclc` their micro-ROS applications for Arduino. Anyways, we should at some point give a try on `rclcpp` on Arduino, because it might not be too difficult to support it at this point.

2020-11-10 06:45 UTC, pablogs9 commented on _docs/overview/features/index.md
> +The combination rcl+rclc is optimized for MCUs. After an initialization phase, it can be used without any dynamic memory allocations. The rclc package provides advanced execution mechanisms allowing
+1

2020-11-10 07:09 UTC, FranFin requested changes

2020-11-10 07:09 UTC, FranFin commented on _docs/overview/features/index_old.md
> +Quality of service settings for handling non-ideal networks | Two QoS semantics, reliable and best-effort semantics, are provided. It can be set at compile-time.
In principle, if creation by reference is used in the underneath middleware implementation, the whole range of QoS beyond reliable and best-effort modes offered by DDS can be used. This page can be linked: https://micro-ros.github.io/docs/tutorials/core/create_dds_entities_by_ref/.

2020-11-10 07:09 UTC, FranFin commented on _docs/overview/features/index_old.md
> +Build system | Build systems of NuttX, FreeRTOS, and Zephyr are integrated with colcon. Furthermore, micro-ROS is provided as a component for ESP-IDF also as a standalone Zephyr module. The build sys
I'd also mention the Arduino integration here.

2020-11-10 07:09 UTC, FranFin commented on _docs/overview/features/index_old.md
> +Continuous Integration | Currently, the CI for micro-ROS is distributed to GitHub and Gitlab. *Until the end of 2020, all CI should be moved migrated completely to the new CI actions of GitHub.* Plea
```suggestion
Continuous Integration | Currently, the CI for micro-ROS is distributed to GitHub and Gitlab. *Until the end of 2020, all CI should be migrated completely to the new CI actions of GitHub.* Please note that those packages that are released for standard ROS 2 are also built and tested on [build.ros2.org](http://build.ros2.org/).
```

2020-11-10 07:52 UTC, ralph-lange commented on _docs/overview/features/index_old.md
> +Quality of service settings for handling non-ideal networks | Two QoS semantics, reliable and best-effort semantics, are provided. It can be set at compile-time.
I had kept the old file for the draft (and as a basis for the micro-ROS <-> ROS 2 comparison table. Deleted the old file now for clarity.

2020-11-10 07:52 UTC, ralph-lange commented on _docs/overview/features/index_old.md
> +Continuous Integration | Currently, the CI for micro-ROS is distributed to GitHub and Gitlab. *Until the end of 2020, all CI should be moved migrated completely to the new CI actions of GitHub.* Plea
I had kept the old file for the draft (and as a basis for the micro-ROS <-> ROS 2 comparison table. Deleted the old file now for clarity.

2020-11-10 07:52 UTC, ralph-lange commented on _docs/overview/features/index_old.md
> +Build system | Build systems of NuttX, FreeRTOS, and Zephyr are integrated with colcon. Furthermore, micro-ROS is provided as a component for ESP-IDF also as a standalone Zephyr module. The build sys
I had kept the old file for the draft (and as a basis for the micro-ROS <-> ROS 2 comparison table. Deleted the old file now for clarity.

2020-11-11 09:03 UTC, ralph-lange commented
@pablogs9, @FranFin, the feature list is ready for merge from my perspective. I made it collapsible for readability. I removed the graphics on this page as it appeared too distracting to me. Maybe, we can come up with a less distracting image just for visualization.
Please note that I slightly changed the description of the Permissive License feature.

2020-11-11 15:30 UTC, FranFin approved these changes

2020-11-11 15:30 UTC, merged