Adding memory profiling page.
micro-ROS/micro-ROS.github.io pull request #236
Opened 2020-11-16 10:23 UTC by FranFin

2020-11-16 15:20 UTC, ralph-lange requested changes
Very nice report! It's a bit long in my opinion, but there are some redundancies which can be removed to shorten it. I marked them in my comments.

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +![Pubsub diagram](pubsub_diagram.png)
Should this image to be centered like the next one in line 67?

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +<img alt="Services diamgram" src="services_diagram.png" class="center" width="50%">
```suggestion
<img alt="Services diagram" src="services_diagram.png" class="center" width="50%">
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +![Pubsub diagram](pubsub_diagram.png)
```suggestion
![Pub/sub diagram](pubsub_diagram.png)
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +The stack is the memory consumed by the functions used by the program, when executing. Whilst the static memory can be straightforwardly calculated by just analyzing the compiled binary objects, the
```suggestion
The stack is the memory consumed by the functions used by the program, when executing. Whilst the static memory can be straightforwardly calculated by just analyzing the compiled binary objects, the stack is the chunk of memory one cannot know precisely before running the application. The stack consumed during the program execution is taken into account by means of a FreeRTOS specific function involved in the memory management capabilities offered by this RTOS, the `uxTaskGetStackHighWaterMark()` function. This function returns the amount of stack that remains unused when the stack consumed by the program is at its greatest value. By subtracting this figure to the total stack available, which is known, one can obtain the stack peak used by the app.
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +In this section, we summarize the experimental set-up and the different scenarios explored in order to provide a comprehensive review on the memory footprint of the micro-ROS library.
```suggestion
In this section, we summarize the experimental setup and the different scenarios explored in order to provide a comprehensive review on the memory footprint of the micro-ROS library.
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +* The topic size (in the form of an array of bytes of variable size)
Does topic size mean the message size (i.e. the size of the messages on the topic) or is there more to it? If no, I propose to simply write _message size_.

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +In the first setup, we analyse the total memory consumption of applications that publish or subscribe to topics of variable size while sweeping through the number of entities (publishers and subscrib
```suggestion
In the first setup, we analyse the total memory consumption of applications that publish or subscribe to topics of variable size while sweeping through the number of entities (publishers and subscribers) and employ UDP transport. We do so for the two different QoS types, Reliable and Best-Effort.
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +The number of publishers/subscribers has been varied between 1, 5, 10 and 15. Notice that this is equivalent to changing the number of topics, since in our design of the set-up we associate each publ
The numbers 1, 5, 10, and 15 were already given a few paragraphs before. This repetition should be removed in my opinion.

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +In principle, in the Reliable case one can occupy the generated buffers with topic sizes up to MTU * XRCE_history, whereas in the Best-Effort case it can be filled with topics up to MTU, which corres
```suggestion
In principle, in the Reliable case one can occupy the generated buffers with topic sizes up to MTU &#215; XRCE_history, whereas in the Best-Effort case it can be filled with topics up to MTU, which correspond respectively to to 512 B &#215; 4 = 2048 B and 512 B with our default chosen values. This is due to the absence of fragmentation in Best-Effort communication streams, while, thanks to fragmentation, an entity functioning in Reliable mode can send/receive a message opportunely chunked in a number of pieces equal to the XRCE_history, each of the size of the MTU. However, from table 1 one can see the topic size only ranges from 0 and 1366 B in the case of Reliable entities, and between 0 and 490 B for entities in Best-Effort mode. This is due to the fact that in both cases some memory is consumed by headers and, most importantly, in the Reliable case some is consumed by confirmation messages such as heartbeats and acknacks.
```

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +The total memory consumed by a micro-ROS application running on a MCU (in this specific case, the ESP32 used for testing) can be calculated as the direct sum of different chunks of memory, each devot
```suggestion
The total memory consumed by a micro-ROS application running on a MCU can be calculated as the direct sum of different chunks of memory, each devoted to a different function: static memory, stack and dynamic memory.
```
Use of the ESP32 is explained at the very beginning as the results are probably quite independent of the MCU, I would not repeat it here.

2020-11-16 15:20 UTC, ralph-lange commented on _docs/concepts/memo_prof/index.md
> +All the tested apps run on top of FreeRTOS and inside of an ESP32 board. The board is connected by either UDP or serial transport to a micro-ROS Agent running on a Linux machine. As explained above,
Probably the ESP32 can then be omitted in the abstract.

2020-11-16 15:47 UTC, FranFin commented on _data/docs.yml
> +- title: Memory profiling
It covers the middleware and the RMW, so I'd say it doesn't properly belong to the Client Library section. On the other hand, I like the idea of putting it together with the benchmarking. However, we decided to remove the section and subsection structure, and leave only a few independent sections, same as in the Overview part. Do we want to go through with it or do we prefer to group topics under common sections as it is right now?

2020-11-16 16:05 UTC, FranFin commented on _docs/concepts/memo_prof/index.md
> +* The topic size (in the form of an array of bytes of variable size)
Ok, changed most of them. Sometimes I still refer to "topic" anyways.

2020-11-16 16:07 UTC, FranFin commented on _docs/concepts/memo_prof/index.md
> +All the tested apps run on top of FreeRTOS and inside of an ESP32 board. The board is connected by either UDP or serial transport to a micro-ROS Agent running on a Linux machine. As explained above,
I think it's normal to repeat something that is already said in the Abstract, so I'd leave that. But I definitely took away its previous occurrence.

2020-11-17 06:57 UTC, ralph-lange approved these changes

2020-11-23 11:00 UTC, merged