Feature/creative commons
micro-ROS/micro-ROS.github.io pull request #237
Opened 2020-11-16 14:03 UTC by FranFin

2020-11-16 15:23 UTC, ralph-lange requested changes

2020-11-16 15:23 UTC, ralph-lange commented on README.md
> +**Share** — copy and redistribute the material in any medium or format for any purpose, even commercially.
```suggestion
* **Share** — copy and redistribute the material in any medium or format for any purpose, even commercially.
```

2020-11-16 15:23 UTC, ralph-lange commented on README.md
> +**Attribution** — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the lice
```suggestion
* **Attribution** — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
```

2020-11-16 15:23 UTC, ralph-lange commented on README.md
> +**NoDerivatives** — If you remix, transform, or build upon the material, you may not distribute the modified material.
```suggestion
* **NoDerivatives** — If you remix, transform, or build upon the material, you may not distribute the modified material.
```

2020-11-16 15:23 UTC, ralph-lange commented on README.md
> +**No additional restrictions** — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
```suggestion
* **No additional restrictions** — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
```
..., i.e. make the restrictions a list.

2020-11-17 06:58 UTC, ralph-lange approved these changes

2020-11-23 10:59 UTC, pablogs9 approved these changes

2020-11-23 11:00 UTC, merged