Rework hardware page
micro-ROS/micro-ROS.github.io pull request #241
Opened 2020-11-24 09:26 UTC by pablogs9

2020-11-26 06:37 UTC, FranFin requested changes

2020-11-26 06:37 UTC, FranFin commented on _docs/overview/hardware/index.md
> +The main targets of micro-ROS are mid-range 32-bits microcontroller families. Usually, the minimum requirements for running micro-ROS in an embedded platform are memory constrains. Since memory usage
```suggestion
The main targets of micro-ROS are mid-range 32-bits microcontroller families. Usually, the minimum requirements for running micro-ROS in an embedded platform are memory constrains. Since memory usage in micro-ROS is a complex matter we provide a [complete article](https://micro-ros.github.io/docs/concepts/memo_prof/) describing it and a tutorial on [how to tune the memory consuption](https://micro-ros.github.io/docs/tutorials/core/microxrcedds_rmw_configuration/) in the micro-ROS middleware. 
```

2020-11-26 06:37 UTC, FranFin commented on _docs/overview/hardware/index.md
> +In general micro-ROS will need MCU that have tens of kilobytes of RAM memory and communication peripherals that enables the micro-ROS [client to agent communication](https://micro-ros.github.io//docs
```suggestion
In general micro-ROS will need MCUs that have tens of kilobytes of RAM memory and communication peripherals that enable the micro-ROS [Client to Agent communication](https://micro-ros.github.io//docs/overview/features/).
```

2020-11-26 06:37 UTC, FranFin commented on _docs/overview/hardware/index.md
> +*In order to check the most recent hardware support visit the [micro_ros_setup repo](https://github.com/micro-ROS/micro_ros_setup)*
```suggestion
*In order to check the most recent hardware support visit the [micro_ros_setup repo](https://github.com/micro-ROS/micro_ros_setup)*.
```

2020-11-26 06:37 UTC, FranFin commented on _docs/overview/hardware/index.md
> +The micro-ROS reference boards are the one officially supported for all RTOS with complete support for all available transports.
```suggestion
The micro-ROS reference boards are the ones officially supported for all RTOSes and with complete support for all available transports.
```

2020-11-26 06:37 UTC, FranFin commented on _docs/overview/hardware/index.md
> +The micro-ROS Tier 2 boards are officially suported boards for one or more RTOS or transports.
```suggestion
The micro-ROS Tier 2 boards are officially supported for one or more RTOSes and transports.
```

2020-11-26 07:10 UTC, jamoralp commented on _docs/overview/hardware/index.md
> +The main targets of micro-ROS are mid-range 32-bits microcontroller families. Usually, the minimum requirements for running micro-ROS in an embedded platform are memory constrains. Since memory usage
```suggestion
The main targets of micro-ROS are mid-range 32-bits microcontroller families. Usually, the minimum requirements for running micro-ROS in an embedded platform are memory constraints. Since memory usage in micro-ROS is a complex matter we have a [complete article](https://micro-ros.github.io/docs/concepts/memo_prof/) describing it and a tutorial on [how to tune the memory consuption](https://micro-ros.github.io/docs/tutorials/core/microxrcedds_rmw_configuration/) in the micro-ROS middleware. 
```

2020-11-26 07:10 UTC, jamoralp commented on _docs/overview/hardware/index.md
> +The micro-ROS hardware support is divided in three categories:
```suggestion
The micro-ROS hardware support is divided into three categories: 
```

2020-11-26 08:39 UTC, jamoralp submitted a review, later dismissed

2020-11-26 12:38 UTC, FranFin submitted a review, later dismissed

2020-12-02 08:48 UTC, FranFin approved these changes

2020-12-02 08:53 UTC, jamoralp approved these changes

2020-12-02 11:04 UTC, ralph-lange approved these changes

2020-12-02 14:16 UTC, merged