Rework transports tables
micro-ROS/micro-ROS.github.io pull request #243
Opened 2020-11-24 10:02 UTC by pablogs9

Before merge:
- [ ] https://github.com/micro-ROS/micro-ROS.github.io/pull/241

2020-11-24 13:00 UTC, ralph-lange requested changes

2020-11-24 13:00 UTC, ralph-lange commented on _docs/overview/transports/index.md
> +The following table specifies the available transports for the **officially supported** boards and RTOS. You can find detailed information about hardware support [here](/docs/overview/hardware/).
```suggestion
The following table specifies the available transports for the Reference and Tier-2 micro-ROS boards for each officially supported RTOS. You can find detailed information about hardware support [here](/docs/overview/hardware/).
```

2020-11-24 14:12 UTC, pablogs9 commented on _docs/overview/hardware/index.md
> +    <img src="imgs/teensy41.jpg">
Done

2020-11-24 14:13 UTC, pablogs9 commented on _docs/overview/hardware/index.md
> +
Done

2020-11-24 14:13 UTC, pablogs9 commented on _docs/overview/hardware/index.md
> +
Done

2020-11-24 14:13 UTC, pablogs9 commented on _docs/overview/hardware/index.md
> +
Done

2020-11-25 08:36 UTC, ralph-lange submitted a review, later dismissed

2020-11-26 06:50 UTC, FranFin requested changes

2020-11-26 06:50 UTC, FranFin commented on _docs/overview/transports/index.md
> +It supports are variety of data link and transport protocols. However, the support depends on the underlying RTOS and the selected hardware.
```suggestion
It supports a variety of data link and transport protocols. However, the support depends on the underlying RTOS and selected hardware.
```

2020-11-26 08:37 UTC, jamoralp approved these changes

2020-11-26 12:40 UTC, FranFin approved these changes

2020-12-02 11:03 UTC, ralph-lange submitted a review, later dismissed

2020-12-02 11:36 UTC, FranFin approved these changes

2020-12-02 14:16 UTC, merged