Adding build systems section
micro-ROS/micro-ROS.github.io pull request #244
Opened 2020-11-24 11:26 UTC by pablogs9

2020-11-26 07:14 UTC, jamoralp requested changes

2020-11-26 07:14 UTC, jamoralp commented on _docs/concepts/build_system/index.md
> +It is possible to obtain a list of the supported hardware by running the command without any argument. By soing so, it possible to see that along with the RTOSes and hardware supported by micro-ROS t
```suggestion
It is possible to obtain a list of the supported hardware by running the command without any argument. By doing so, it is possible to see that along with the RTOSes and hardware supported by micro-ROS this build system also provides with three extra options:
```

2020-11-26 07:14 UTC, jamoralp commented on _docs/concepts/build_system/index.md
> +Once the build system has create the new firmware project, it is possible to configure it using:
```suggestion
Once the build system has created the new firmware project, it is possible to configure it using:
```

2020-11-26 07:15 UTC, FranFin requested changes

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +- using the **micro_ros_setup** as a tool integrated in a ROS 2 workspace
```suggestion
- using the **micro_ros_setup** as a tool integrated in a ROS 2 workspace.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +**micro_ros_setup** provides an standalone build system in the form of a ROS 2 package that can be integrated in a common ROS 2 workspace. This tool is available in [micro-ROS/micro_ros_setup](https:
```suggestion
**micro_ros_setup** provides a standalone build system in the form of a ROS 2 package that can be integrated in a common ROS 2 workspace. This tool is available in the [micro-ROS/micro_ros_setup](https://github.com/micro-ROS/micro_ros_setup) repository in GitHub.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +The micro_ros_setup tools is in charge of generating micro-ROS images that contains micro-ROS apps for the [supported hardware](/docs/overview/hardware/) boards and [RTOS](/docs/concepts/rtos/).
```suggestion
The **micro_ros_setup** tool is in charge of generating micro-ROS images that contain micro-ROS apps for the [supported hardware](/docs/overview/hardware/) boards and [RTOSes](/docs/concepts/rtos/).
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +As the micro_ros_setup package can be installed as any other ROS 2 package its usage will be through the ROS 2 CLI tool. For example in order to install the micro-ROS build system in a ROS 2 workspac
```suggestion
As the **micro_ros_setup** package can be installed like any other ROS 2 package, its usage will be through the ROS 2 CLI tool. For example in order to install the micro-ROS build system in a ROS 2 workspace just download it and build it with `colcon`:
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +Once it is installed the build system tool has some utilities that can be used in order to prepare, build, flash and use a micro-ROS application. The micro-ROS buils system is a four step procedure.I
```suggestion
Once installed, the build system tool provides some utilities that can be used in order to prepare, build, flash and use a micro-ROS application. The micro-ROS build system is a four-step procedure. In the first step, the user can create a new micro-ROS application by configuring the target hardware and RTOS:
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +It is possible to obtain a list of the supported hardware by running the command without any argument. By soing so, it possible to see that along with the RTOSes and hardware supported by micro-ROS t
```suggestion
It is possible to obtain a list of the supported hardware by running the command without any argument. By doing so, it is possible to see that, along with the RTOSes and hardware supported by micro-ROS, the build system also provides three extra options:
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +- By using just `host` as RTOS, micro-ROS will build a set of [micro-ROS demo applications](https://github.com/micro-ROS/micro-ROS-demos) natively in your host machine. This applications behaves just
```suggestion
- By using just `host` as RTOS, micro-ROS will build a set of [micro-ROS demo applications](https://github.com/micro-ROS/micro-ROS-demos) natively in your host machine. These applications behave just like micro-ROS apps (using the same abstraction layers and middleware implementation) and allow the user to debug and test the applications on a PC.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +Once the build system has create the new firmware project, it is possible to configure it using:
```suggestion
Once the build system has created the new firmware project, it is possible to configure it using:
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +Running this command without any argument it will output a list of example application valid for the selected RTOS.
```suggestion
By running this command without any argument, it will output a list of example applications valid for the selected RTOS.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +The micro-ROS build system is also able to ease the compilation of the micro-ROS Agent in a ROS 2 workspace using these commands:
```suggestion
The micro-ROS build system is also able to ease the compilation of the micro-ROS Agent in a ROS 2 workspace by using these commands:
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
```suggestion
***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/external_build_systems/index.md
> +Once you have read about the oficial[ **micro_ros_setup** tool](/docs/concepts/build_system/), this page will present some other approaches for building micro-ROS as a module or component integrated
```suggestion
Once you have read about the official[ **micro_ros_setup** tool](/docs/concepts/build_system/), this page will present some other approaches for building micro-ROS as a module or component integrated into other build systems.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/external_build_systems/index.md
> +The procedure for configuring the built micro-ROS library is based in `colcon.meta`. For more details visit the [Github repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```suggestion
Configuration of the micro-ROS library is based on the `colcon.meta` file. For more details visit the [Github repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/external_build_systems/index.md
> +The [micro-ROS for Arduino](https://github.com/micro-ROS/micro_ros_arduino) support package is a special port of micro-ROS provided as a set of precompiled libraries for specific platforms. The main
```suggestion
The [micro-ROS for Arduino](https://github.com/micro-ROS/micro_ros_arduino) support package is a special port of micro-ROS provided as a set of precompiled libraries for specific platforms. The main reason for this approach is that Arduino does not allow the build of a complex library such as micro-ROS, so by using this approach a ready-to-use solution is provided to the Arduino users.
```

2020-11-26 07:15 UTC, FranFin commented on _docs/concepts/build_system/external_build_systems/index.md
> +Along with this support package there are [detailed instructions](https://github.com/micro-ROS/micro_ros_arduino#how-to-build-the-precompiled-library) for rebuilding the micro-ROS for Arduino librari
```suggestion
Along with this support package, there are [detailed instructions](https://github.com/micro-ROS/micro_ros_arduino#how-to-build-the-precompiled-library) for rebuilding micro-ROS for Arduino libraries for users that need to tune the default configuration.
```

2020-11-26 08:36 UTC, jamoralp approved these changes

2020-11-26 12:40 UTC, FranFin approved these changes

2020-11-27 07:28 UTC, ralph-lange requested changes

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/external_build_systems/index.md
> +Once you have read about the official[ **micro_ros_setup** tool](/docs/concepts/build_system/), this page will present some other approaches for building micro-ROS as a module or component integrated
```suggestion
Once you have read about the official [**micro_ros_setup** tool](/docs/concepts/build_system/), this page will present some other approaches for building micro-ROS as a module or component integrated into other build systems.
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/external_build_systems/index.md
> +The [micro-ROS module for Zephyr](https://github.com/micro-ROS/micro_ros_zephyr_module) allows to integrate micro-ROS as a module in a Zephyr RTOS project. This component allows the user to integrate
```suggestion
The [micro-ROS module for Zephyr](https://github.com/micro-ROS/micro_ros_zephyr_module) allows to integrate micro-ROS as a module in a Zephyr-based project. In detail, it enables to integrate the micro-ROS API and utilities in an existing Zephyr project just by cloning or copying a folder.
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/external_build_systems/index.md
> +Configuration of the micro-ROS library is based on the `colcon.meta` file. For more details visit the [Github repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```suggestion
Configuration of the micro-ROS library is based on the `colcon.meta` file. For more details visit the [Git repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```

Either just Git or GitHub with correct capitalization, but I would avoid the name GitHub here.

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/external_build_systems/index.md
> +The procedure for configuring the built micro-ROS library is based in `colcon.meta`. For more details visit the [Github repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```suggestion
The procedure for configuring the built micro-ROS library is based in `colcon.meta`. For more details visit the [Git repository](https://github.com/micro-ROS/micro_ros_espidf_component).
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +- using the **micro_ros_setup** as a tool integrated in a ROS 2 workspace.
```suggestion
- _micro_ros_setup:_ integrates and hides the RTOS-specific build tools in few scripts provided as a ROS 2 package.
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +- using external integrations tools. Click [here](/docs/concepts/build_system/external_build_systems/) for more details about this option.
```suggestion
_RTOS-specific integrations:_ We have integrated micro-ROS with several RTOS build tools. Click [here](/docs/concepts/build_system/external_build_systems/) to learn more.
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +**micro_ros_setup** provides a standalone build system in the form of a ROS 2 package that can be integrated in a common ROS 2 workspace. This tool is available in the [micro-ROS/micro_ros_setup](htt
```suggestion
**micro_ros_setup** provides a standalone build system in the form of a ROS 2 package for use in any normal ROS 2 workspace. This tool is available in the [micro-ROS/micro_ros_setup](https://github.com/micro-ROS/micro_ros_setup) repository.
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +The **micro_ros_setup** tool is in charge of generating micro-ROS images that contain micro-ROS apps for the [supported hardware](/docs/overview/hardware/) boards and [RTOSes](/docs/concepts/rtos/).
```suggestion
The **micro_ros_setup** tool allows compiling and generating images that contain micro-ROS apps for the [supported hardware](/docs/overview/hardware/) boards and [RTOSes](/docs/concepts/rtos/).
```

2020-11-27 07:28 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +As the **micro_ros_setup** package can be installed like any other ROS 2 package, its usage will be through the ROS 2 CLI tool. For example in order to install the micro-ROS build system in a ROS 2 w
There is some overlap with the tutorial, or? I propose to minimize any redundancy on the website (for maintenance reasons) and simply refer to the tutorial from hereon, but feel free to illustrate the simplicity by a sentence like "Compiling, generating an image and flashing it on a board is just four commands `ros2 run micro_ros_setup create_firmware, configure_firmware build_firmware, and flash_firmware`" or similar.

2020-11-27 08:11 UTC, pablogs9 commented on _docs/concepts/build_system/index.md
> +As the **micro_ros_setup** package can be installed like any other ROS 2 package, its usage will be through the ROS 2 CLI tool. For example in order to install the micro-ROS build system in a ROS 2 w
I have removed some sections, let me know if is ok for you. We are merging when you approve. Thanks Ralph!

2020-11-27 08:19 UTC, ralph-lange requested changes

2020-11-27 08:19 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +
```suggestion

**Tip 1:** To learn use of the micro_ros_setup build system hands-on, please see the [core tutorials](https://micro-ros.github.io/docs/tutorials/core/first_application_rtos/).

```

2020-11-27 08:19 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
```suggestion
**Tip 2 :** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`
```

2020-11-27 08:19 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +As the **micro_ros_setup** package can be installed like any other ROS 2 package, its usage will be through the ROS 2 CLI tool. Compiling, generating an image and flashing it on a board can be done j
```suggestion
As the **micro_ros_setup** package can be installed like any other ROS 2 package, its usage will be through the ROS 2 CLI tool. Compiling, generating an image and flashing it on a board can be done just with four ROS 2 commands. A detailed description about the usage of this package can be found in the [tutorial section](/docs/tutorials/core/first_application_rtos/).
```

2020-11-27 08:23 UTC, pablogs9 commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
Sorry Ralph, which is the Tip 1?

2020-11-27 08:25 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
The one in line 67 :-)

2020-11-27 08:27 UTC, ralph-lange commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
I know that you have added a pointer to the tutorial above, but I think it's a good idea to point the reader again to the tutorial once he/she reached the bottom of the page.

2020-11-27 08:30 UTC, pablogs9 commented on _docs/concepts/build_system/index.md
> +***TIP:** Remember that the micro-ROS Agent can be also be used with this simple Docker command: `docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy [OPTIONS]`*
Cool, I'm including also this.

2020-11-27 08:45 UTC, ralph-lange approved these changes

2020-11-27 09:46 UTC, merged