Feature/memprof under benchmark
micro-ROS/micro-ROS.github.io pull request #245
Opened 2020-11-24 11:42 UTC by FranFin

This PR groups the new sections into with the old `benchmarking` section has been split (`concept` and `result`) and the new `memo_prof` page under the same tab `benchmarking`.

2020-11-24 12:50 UTC, ralph-lange submitted a review, later dismissed

2020-11-25 07:36 UTC, walkiry commented
@FranFin Do you think it would be worth to mention within the benchmarking result the profiling results?

2020-11-25 07:37 UTC, walkiry approved these changes

2020-11-26 06:58 UTC, FranFin commented
@walkiry You mean just a sentence referring to the Memory Profiling page? That's fine with me!

2020-11-26 07:06 UTC, jamoralp requested changes

2020-11-26 07:06 UTC, jamoralp commented on _docs/concepts/benchmarking/benchmarking/index.md
> + * Provide snippets codes that will be added for benchmarking.
```suggestion
 * Provide snippet codes that will be added for benchmarking.
```

2020-11-26 07:06 UTC, jamoralp commented on _docs/concepts/benchmarking/benchmarking/index.md
> +This section will introduce some concept related to the shadow builder (SB).
```suggestion
This section will introduce some concepts related to the shadow builder (SB).
```

2020-11-26 07:06 UTC, jamoralp commented on _docs/concepts/benchmarking/benchmarking/index.md
> + * Compile the targeted binary for different platform.
```suggestion
 * Compile the targeted binary for different platforms.
```

2020-11-26 07:06 UTC, jamoralp commented on _docs/concepts/benchmarking/benchmarking/index.md
> +appropriate sources
That sentence is incomplete
```suggestion
And if the benchmarking is not activated, it should be bypassed.
```

2020-11-26 07:06 UTC, jamoralp commented on _docs/concepts/benchmarking/benchmarking/index.md
> +user in the benchmarking configuration file.  Injecting code
```suggestion
user in the benchmarking configuration file.
```

2020-11-26 07:06 UTC, pablogs9 approved these changes

2020-11-27 05:29 UTC, amx-piap submitted a review, later dismissed

2020-11-27 12:33 UTC, jamoralp approved these changes

2020-12-02 11:03 UTC, ralph-lange approved these changes

2020-12-02 14:20 UTC, merged