Feature/update features comparison with ros2
micro-ROS/micro-ROS.github.io pull request #247
Opened 2020-11-25 14:52 UTC by FranFin

Comments:

- New features introduced in the table.
- Updated/changed the description of some previous features.
- Set of symbols used updated and legend created below.
- Table split into sub-tables according to macro-categories defined in "Features and Architecture" section.
- Swapped the order of two elements in the "Features and Architecture" section so as to generate a better match with the new comparison table.

2020-11-25 15:17 UTC, pablogs9 requested changes

2020-11-25 15:17 UTC, pablogs9 commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Comparison of micro-ROS features with ROS 2 features. The following list has been compiled from [https://index.ros.org/doc/ros2/Features/](https://index.ros.org/doc/ros2/Features/) and [https://index
careful with `localhost`
```suggestion
Comparison of micro-ROS features with ROS 2 features. The following list has been compiled from [https://index.ros.org/doc/ros2/Features/](https://index.ros.org/doc/ros2/Features/) and [https://index.ros.org/doc/ros2/Roadmap/](https://index.ros.org/doc/ros2/Roadmap/), and the features have been organized into sub-tables according to the macrocategories defined in the [Features and Architecture page](/overview/features/).
```

2020-11-25 15:17 UTC, pablogs9 commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) fr
```suggestion
Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) from ROS 2 as-is. The [rclc](https://github.com/micro-ROS/rclc) package provides convenience functions and an executor for use of RCL + RCLC as client library for the C programming language. *Roadmap: migrate all functionalities to the rclc, so as to make it an independent abraction layer on top of the rcl that serves as user's API.*
```

2020-11-25 15:18 UTC, pablogs9 commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) fr
I'm not sure, but if we decide to use a capitalized version, there are multiple places where there are `rclc` in lower case.

2020-11-25 17:00 UTC, ralph-lange commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Comparison of micro-ROS features with ROS 2 features. The following list has been compiled from [https://index.ros.org/doc/ros2/Features/](https://index.ros.org/doc/ros2/Features/) and [https://index
... but the `/docs/` must be kept.

2020-11-25 17:04 UTC, ralph-lange commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) fr
I always use lower case and write "Rcl" or "Rclc" only at the beginning of a sentence.

At index.ros.org, it seems to be written lower case in the majority of cases:
https://index.ros.org/search/?term=rcl&section=docs

And, rclcpp and rclpy are always written lower case:
https://index.ros.org/search/?term=rclcpp&section=docs

2020-11-26 06:37 UTC, jamoralp commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) fr
```suggestion
Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) from ROS 2 as-is. The [rclc](https://github.com/micro-ROS/rclc) package provides convenience functions and an executor for use of rcl+rclc as client library for the C programming language. *Roadmap: migrate all functionalities to the rclc, so as to make it an independent absraction layer on top of the rcl that serves as user's API.*
```

2020-11-26 06:37 UTC, jamoralp commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Build system | <span class="status_flag">&#10003;</span> | micro-ROS provides two ways of building a micro-ROS application. The first uses the [micro_ros_setup](https://github.com/micro-ROS/micro_ros
```suggestion
Build system | <span class="status_flag">&#10003;</span> | micro-ROS provides two ways of building a micro-ROS application. The first uses the [micro_ros_setup](https://github.com/micro-ROS/micro_ros_setup) tool integrated in a ROS 2 workspace. With this approach, the build systems of NuttX, FreeRTOS, and Zephyr are integrated with colcon. The other provides micro-ROS as a component for external development frameworks (e.g., ESP-IDF and Zephyr build system).
```

2020-11-26 06:37 UTC, jamoralp commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Supported hardware | <span class="status_flag">&#10003;</span> | micro-ROS officially supports four boards. For the moments, all official ports are based on the STM32 series from ST and on the ESP32
```suggestion
Supported hardware | <span class="status_flag">&#10003;</span> | micro-ROS officially supports four boards. For the moment, all official ports are based on the STM32 series from ST and on the ESP32 from Espressif. Find more info [here](https://micro-ros.github.io/docs/overview/hardware/). More ports have been carried out by users, check the [complete list](https://github.com/micro-ROS/micro_ros_setup#supported-platforms).
```

2020-11-26 06:37 UTC, jamoralp commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Peer-to-peer functionality | <span class="status_flag">&#10003;&#8728;</span> | Prototypical peer-to-peer functionality implemented over boradcast. No QoS available for the moment. *Roadmap: improve
```suggestion
Peer-to-peer functionality | <span class="status_flag">&#10003;&#8728;</span> | Prototypical peer-to-peer functionality implemented over broadcast. No QoS available for the moment. *Roadmap: improve prototype to achieve true point-to-point connection.*
```

2020-11-26 07:10 UTC, pablogs9 commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Comparison of micro-ROS features with ROS 2 features. The following list has been compiled from [https://index.ros.org/doc/ros2/Features/](https://index.ros.org/doc/ros2/Features/) and [https://index
Suggested fix fixed

2020-11-26 07:10 UTC, pablogs9 commented on _docs/overview/ROS_2_feature_comparison/index.md
> +Common core client library that is wrapped by language-specific libraries | <span class="status_flag">&#10003;&#8728;</span> | Use of the client support library [rcl](https://github.com/ros2/rcl/) fr
Resolving conversation, I'm ok with lowercase

2020-11-27 06:42 UTC, ralph-lange submitted a review, later dismissed

2020-11-27 06:57 UTC, ralph-lange approved these changes

2020-11-27 07:00 UTC, jamoralp approved these changes

2020-11-27 07:16 UTC, pablogs9 approved these changes

2020-11-27 07:19 UTC, merged