Update Docker and CI status tables and content
micro-ROS/micro-ROS.github.io pull request #248
Opened 2020-11-30 07:22 UTC by jamoralp

2020-12-02 07:24 UTC, FranFin submitted a review, later dismissed

2020-12-02 07:30 UTC, ralph-lange requested changes

2020-12-02 07:30 UTC, ralph-lange commented on _docs/overview/docker_ci_status/index.md
> +  * Extensions to rcl, i.e. the ROS 2 Client Library C API: [rcl_executor](https://github.com/micro-ROS/rcl_executor), [rclc](https://github.com/micro-ROS/rclc)...
```suggestion
  * Extensions to rcl, i.e. the ROS 2 Client Library C API: [rclc](https://github.com/micro-ROS/rclc)
```

2020-12-02 07:41 UTC, pablogs9 commented
Reorder proposal:

1. CI Status for Tooling and Website
  Add here issues and PR counters, maybe the webpage repo should be removed from here.
2. CI Status for Source Code Repositories
3. CI Status for Example Application Repositories
4. Docker Images Status


Aditionally I will remove the "CI Status" since we are also showing issues and PR. Just "Status"?

2020-12-02 09:05 UTC, jamoralp commented
> Reorder proposal:
> 
> 1. CI Status for Tooling and Website
>    Add here issues and PR counters, maybe the webpage repo should be removed from here.
> 2. CI Status for Source Code Repositories
> 3. CI Status for Example Application Repositories
> 4. Docker Images Status
> 
> Additionally I will remove the "CI Status" since we are also showing issues and PR. Just "Status"?

Ok, the order sounds good for me. I also believe the Docker section is not so-to-say "relevant" and can be moved to a less important spot in the resulting webpage.

2020-12-02 14:05 UTC, jamoralp commented
@pablogs9 @FranFin @ralph-lange I reworked the section completely, and unified the tables' contents. Please re-review.

2020-12-02 14:07 UTC, pablogs9 submitted a review, later dismissed

2020-12-02 14:29 UTC, pablogs9 approved these changes

2020-12-03 07:39 UTC, ralph-lange approved these changes

2020-12-03 08:14 UTC, merged