Reworked concepts/middleware section.
micro-ROS/micro-ROS.github.io pull request #259
Opened 2020-12-10 11:35 UTC by FranFin

Changes addressed:
- Updated text (e. g. mention FreeRTOS and Zephyr, link ‘Middleware Configuration’, mention rmw_microxrcedds and link readme, link ‘custom QoS’ tutorial) in Micro XRCE-DDS section
- Added memory profiling of Micro XRCE-DDS
- Changed micro-ROS to Micro XRCE-DDS in "micro-ROS compared to rosserial" section

2020-12-10 11:38 UTC, FranFin commented
**Note:** Tests are failing because I have used links that will be created only when this PR is merged.

2020-12-10 11:45 UTC, jamoralp requested changes

2020-12-10 11:45 UTC, jamoralp commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +As it was mentioned above, Micro XRCE-DDS is focused on microcontroller applications. Therefore, the design and implementation of this middleware have been carried out taking into account the memory
```suggestion
As it was mentioned above, Micro XRCE-DDS is focused on microcontroller applications. Therefore, the design and implementation of this middleware has been carried out taking into account the memory constraints of this kind of devices.
```

2020-12-10 11:45 UTC, jamoralp commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +Moreover, this library is highly configurable thanks a *profile* concept that enables to choose, add or remove some features in configuration time. That allows customizing the XRCE Client library siz
```suggestion
Moreover, this library is highly configurable thanks to a *profile* concept that enables to choose, add or remove some features in configuration time. That allows customizing the XRCE Client library size, if there are features that are not used.
```

2020-12-10 11:45 UTC, jamoralp commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +Ideed, in contrast to other IoT middleware such as MQTT and CoaP, which work over only a particular transport layer, XRCE supports multiple transport protocols natively.
```suggestion
Indeed, in contrast to other IoT middleware such as MQTT and CoaP, which work over only a particular transport layer, XRCE supports multiple transport protocols natively.
```

2020-12-10 11:45 UTC, jamoralp commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +Apart from this, Micro XRCE-DDS has a transport interface for both Agent and Client which allows to implement custom transport in an straightforward manner.
```suggestion
Apart from this, Micro XRCE-DDS has a transport interface for both Agent and Client which allows to implement custom transports in a straightforward manner.
```

2020-12-10 11:45 UTC, jamoralp commented on _docs/concepts/middleware/rosserial/index.md
> +The elibraries in charge of implementing this architecture are the Client and the Agent.
```suggestion
The libraries in charge of implementing this architecture are the Client and the Agent.
```

2020-12-10 11:47 UTC, jamoralp commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +For more detailed information on the memory consumption as a function of message size, entity number and internal memory management of the middleware library, please refer to the [Micro XRCE-DDS memo
I think you can use this approach to avoid the CI to failing. Also this is more maintainable.

```suggestion
For more detailed information on the memory consumption as a function of message size, entity number and internal memory management of the middleware library, please refer to the [Micro XRCE-DDS memory profiling](concepts/middleware/memo_prof/) section.
```

2020-12-10 11:51 UTC, FranFin commented on _docs/concepts/middleware/Micro_XRCE-DDS/index.md
> +As it was mentioned above, Micro XRCE-DDS is focused on microcontroller applications. Therefore, the design and implementation of this middleware have been carried out taking into account the memory
The subject is plural.

2020-12-15 08:38 UTC, pablogs9 approved these changes

2020-12-15 08:45 UTC, jamoralp approved these changes

2020-12-15 08:51 UTC, merged