Reworked RTOS pages both in Concepts and Overview sections.
micro-ROS/micro-ROS.github.io pull request #261
Opened 2020-12-10 16:08 UTC by FranFin

2020-12-11 07:52 UTC, pablogs9 requested changes

2020-12-11 07:52 UTC, pablogs9 commented on _docs/concepts/rtos/index.md
> +Like the Operating Systems (OSes) available for computers, the RTOSes also have different support for standard interfaces. This is established in a family of standards named [POSIX](https://pubs.open
```suggestion
Like the Operating Systems (OSes) available for computers, the RTOSes also have different support for standard interfaces. This is established in a family of standards named [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/). As we aim to port or reuse code of ROS 2 that was natively coded in Linux (a mostly POSIX-compliant OS), the use of RTOSes that comply with these standards is beneficial, as the porting effort of the code is minimal. Both NuttX and Zephyr comply to a good degree with POSIX standards, making the porting effort minimal, whereas FreeRTOS provides a plugin, *FreeRTOS+POSIX*, thanks to which an existing POSIX compliant application can be easily ported to FreeRTOS ecosystem, and therefore leverage all its functionality.
```

2020-12-11 08:58 UTC, pablogs9 approved these changes

2020-12-15 08:51 UTC, merged

2020-12-15 08:51 UTC, ralph-lange requested changes

2020-12-15 08:51 UTC, ralph-lange commented on _docs/concepts/rtos/comparison/index.md
> +* [FreeRTOS](https://www.freertos.org/index.html)
```suggestion
* [FreeRTOS](https://www.freertos.org/)
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/concepts/rtos/comparison/index.md
>  * Standardized API to Application level
```suggestion
* Standardized API to application level
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/concepts/rtos/comparison/index.md
>  * Supported Hardware
```suggestion
* Supported hardware
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/concepts/rtos/index.md
> +The use of Real-Time Operating Systems (RTOSes) is a general practice in nowadays embedded systems. These devices typically consist of a resource-constrained microcontroller that executes an applicat
```suggestion
The use of Real-Time Operating Systems (RTOSes) is a general practice in nowadays embedded systems. These systems typically consist of a resource-constrained microcontroller that executes an application which requires an interaction with external components. In many cases, this application contains a time-critical task where a strict time deadline or deterministic response is required.
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/concepts/rtos/index.md
> +Due to the benefits presented above, micro-ROS integrates RTOSes in its software stack. The use of such a tool enhances micro-ROS' capabilities and allows reusing all the tools and functions they pro
```suggestion
Due to the benefits presented above, micro-ROS integrates RTOSes in its software stack. This enhances the capabilities of micro-ROS and allows reusing all the tools and functions provided by RTOSes. As the micro-ROS software stack is modular, the exchange of software entities is expected and desired at all levels, including the RTOS layer.
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +### **FreeRTOS**
```suggestion
### FreeRTOS
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +            <li><a href="https://www.freertos.org/index.html">Official FreeRTOS website</a></li>
```suggestion
            <li><a href="https://www.freertos.org/">Official FreeRTOS website</a></li>
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +### **Zephyr**
```suggestion
### Zephyr
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +### **NuttX**
```suggestion
### NuttX
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +NuttX emphasizes its compliance with standards - including POSIX - and small footprint. It can be fit on 8- to 32-bit microcontrollers. The use of POSIX and ANSI standards, together with the mimic it
```suggestion
NuttX emphasizes its compliance with standards - including POSIX - and small footprint. It can be fit on 8- to 32-bit microcontrollers. The use of POSIX and ANSI standards, together with the mimic it does to UNIX APIs, makes it friendly to the developers that are used to Linux. NuttX is licensed under BSD license and makes use of the GNU toolchain. Please note that the uClib++ library used with NuttX comes under the stricter GNU LGPL Version 3 license.
```

2020-12-15 08:51 UTC, ralph-lange commented on _docs/overview/rtos/index.md
> +### **Arduino bare-metal support**
```suggestion
### Arduino bare-metal support
```

2020-12-22 15:02 UTC, FranFin commented on _docs/overview/rtos/index.md
> +### **FreeRTOS**
I actually like it being bold.

2020-12-22 15:02 UTC, FranFin commented on _docs/overview/rtos/index.md
> +### **Zephyr**
Same as above.

2020-12-22 15:02 UTC, FranFin commented on _docs/overview/rtos/index.md
> +### **NuttX**
Same as above.

2020-12-22 15:02 UTC, FranFin commented on _docs/overview/rtos/index.md
> +### **Arduino bare-metal support**
Same as above.