Feature/new blogposts
micro-ROS/micro-ROS.github.io pull request #268
Opened 2020-12-22 15:05 UTC by FranFin

Added several new blogposts.
Addressed changes suggested by Ralph in PR #261.

2020-12-22 15:26 UTC, ralph-lange requested changes
Very nice work, @FranFin!

2020-12-22 15:26 UTC, ralph-lange commented on _posts/2020-11-12-ROS_world.md
> +This year's ROS-Con, due to the pandemic, has been transformed into a virtual event, full of awesome presentations and discussions, the [ROS World 2020 Conference](https://roscon.ros.org/world/2020/)
```suggestion
This year's ROSCon, due to the pandemic, has been transformed into a virtual event, full of awesome presentations and discussions, the [ROS World 2020 Conference](https://roscon.ros.org/world/2020/)!
```

2020-12-22 15:26 UTC, ralph-lange commented on _posts/2020-12-16-ROS-In.md
> +Find the presentations [here](/download/ROS-Industrial_workshop_ROS2.pdf) and [here](/download/ROSIn2020-FrancescaFinocchiaro.pdf).
```suggestion
Find the presentations [here](/download/2020-12-16_Advanced_Execution_Management_with_ROS_2.pdf) and [here](/download/ROSIn2020-FrancescaFinocchiaro.pdf).
```

2020-12-22 15:26 UTC, ralph-lange commented on _posts/2020-12-16-ROS-In.md
> +<embed src="/download/ROS-Industrial_workshop_ROS2.pdf" type="application/pdf" width="100%" height="450px"/>
```suggestion
<embed src="/download/2020-12-16_Advanced_Execution_Management_with_ROS_2.pdf" type="application/pdf" width="100%" height="450px"/>
```

2020-12-22 15:26 UTC, ralph-lange commented on _posts/2020-12-16-ROS-In.md
> +In the first part of the talk, Ralph Lange discussed real-time support and determinism in both ROS 2 and micro-ROS, which is an important requirement for industrial automation. The talk also addresse
```suggestion
In the first part of the talk, Ralph Lange presented the ROS 2 Executor design and discussed latest developments towards real-time support and determinism, which are important requirements for industrial applications. The talk also addressed the most recent features added in the Foxy release and for the Galactic release. Finally, he presented details on the rclc Executor for deeply embedded applications such as those addressed by micro-ROS.
```

2020-12-22 15:28 UTC, ralph-lange commented on _posts/2020-10-05-moveit.md
> +The pose data is then forwarded to the ROS world, where it is consumed by both Rviz and MoveIt. The former uses it directly to represent the position and orientation of the board in its graphical int
```suggestion
The pose data is then forwarded to the ROS world, where it is consumed by both Rviz and MoveIt. The former uses it directly to represent the position and orientation of the board in its graphical interface, while MoveIt uses it to calculate the movement that the virtual arm has to perform to "touch" it, according to its kinematic algorithms for motion planning. The resulting movement is then integrated into Rviz and represented by means of its [virtual Panda robotic arm](https://github.com/ros-planning/panda_moveit_config), a standard tool employed by MoveIt in tutorials and graphic interfaces.
```

2020-12-22 15:29 UTC, ralph-lange commented on _posts/2020-11-18-luxonis.md
> +We’re working with the [LUXonis]() team on the integration of micro-ROS with an exciting AIoT (Artificial Intelligence of Things) project, involving the [DepthAI BW1092 board](https://shop.luxonis.co
```suggestion
We’re working with the [LUXonis](https://luxonis.com/) team on the integration of micro-ROS with an exciting AIoT (Artificial Intelligence of Things) project, involving the [DepthAI BW1092 board](https://shop.luxonis.com/products/bw1092). This small device enables interacting with LUXonis [DepthAI](https://luxonis.com/depthai) SoM from an [ESP32](https://www.espressif.com/en/products/socs/esp32) microcontroller.
```

2020-12-22 15:30 UTC, ralph-lange commented on _posts/2020-11-20-IS.md
> +The second dataspace handles two subscriptors which receive the Twist topic sent by the *teleop_twist_joy node*. The first subscriptor is a Turtlesim application, in charge of displacing the classic
```suggestion
The second dataspace handles two subscriptors which receive the Twist topic sent by the *teleop_twist_joy node*. The first subscriptor is a Turtlesim application, in charge of displacing the classic virtual turtle in its graphical interface according to the indications received by the remote node. The second subscriptions is a micro-ROS Client, communicated with the ROS 2 dataspace via an Agent which allows it to subscribe to the Twist topic. With the data received, micro-ROS is in charge of instructing a Kobuki Turtlebot2, operated by an [ESP32](https://www.espressif.com/en/products/socs/esp32) MCU running [FreeRTOS](https://www.freertos.org/index.html), to move accordingly.
```

2020-12-22 16:06 UTC, FranFin commented
Thanks, @ralph-lange. Just addressed your commentaries!

2020-12-22 16:29 UTC, FranFin commented
Tests are failing due to Twitter links that appear as broken but really are not.

2020-12-23 11:44 UTC, jamoralp approved these changes

2020-12-23 11:45 UTC, merged