Add overview page to advanced tutorials.
micro-ROS/micro-ROS.github.io pull request #304
Opened 2021-04-06 10:02 UTC by FranFin

2021-04-06 12:10 UTC, pablogs9 approved these changes

2021-04-06 14:22 UTC, ralph-lange requested changes
Thank you for creating the new overview page!

2021-04-06 14:22 UTC, ralph-lange commented on _docs/tutorials/advanced/overview/index.md
> +This chapter provides a number of advanced tutorials for those users who already have some previous micro-ROS knowledge. They are useful to interact with micro-ROS at a deeper level if compared with
```suggestion
This chapter provides a number of advanced tutorials for those users who already have some previous micro-ROS knowledge. They are useful to interact with micro-ROS at a deeper level compared with the [**First Step Tutorials**](../../core/overview). There is no specific order recommended to take these tutorials, as each addresses a different aspect of the micro-ROS stack and toolchain.
```

2021-04-06 14:22 UTC, ralph-lange commented on _docs/tutorials/advanced/overview/index.md
> +  In this tutorial, we'll guide you through the configuration of the middleware between a microcontroller and the micro-ROS agent running on some Linux-based microprocessor, to optimize it for your s
```suggestion
  In this tutorial, we'll guide you through the configuration of the middleware between a microcontroller and the micro-ROS agent running on some Linux-based microprocessor, to optimize it for your specific use-case and application.
```

2021-04-06 14:22 UTC, ralph-lange commented on _docs/tutorials/advanced/overview/index.md
> +  This tutorial explains how to create a custom ROS message type to micro-ROS, and then add it to the [build system](https://github.com/micro-ROS/micro_ros_setup).
```suggestion
  This tutorial explains how to create or include a custom ROS message type in a micro-ROS application - and in particular how to bring it into the [build system](https://github.com/micro-ROS/micro_ros_setup).
```

2021-04-07 06:59 UTC, pablogs9 approved these changes

2021-04-07 11:47 UTC, ralph-lange approved these changes

2021-04-07 12:08 UTC, merged