added blog post of ERF 2021
micro-ROS/micro-ROS.github.io pull request #318
Opened 2021-06-23 15:59 UTC by JanStaschulat

tested links and documents with `bundle exec jekyll serve`.

2021-06-23 16:15 UTC, JanStaschulat commented
output of the htlm checker:
`
Checking 779 external links...
Ran on 141 files!
- ./_site/docs/concepts/rtos/comparison/index.html
  *  External link https://interactive.freertos.org/hc/en-us/community/posts/210029046-POSIX-Wrapper-for-FreeRTOS failed: 403 No error
/home/runner/work/micro-ROS.github.io/micro-ROS.github.io/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.15.1/lib/html-proofer/runner.rb:172:in `print_failed_tests': HTML-Proofer found 1 failure! (RuntimeError)
`

but the link `https://interactive.freertos.org/hc/en-us/community/posts/210029046-POSIX-Wrapper-for-FreeRTOS` is correct. 
@pablogs9 any idea?

2021-06-24 05:22 UTC, pablogs9 approved these changes

2021-06-24 05:22 UTC, pablogs9 commented on _posts/2021-04-13-ERF2021.md
> +In this workshop, Francesca Finoccharo (eProsima) presented in detail the micro-ROS architecture, supported platforms and reported recent developments and features: A versatile API for custom transpo
```suggestion
In this workshop, Francesca Finoccharo (eProsima) presented in detail the micro-ROS architecture, supported platforms and reported recent developments and features: A versatile API for custom transports, continuous fragment mode, static memory pools in the RMW and time synchronization between client and agent. ([slides](/download/2021-04-13-ERF-eprosima.pdf))
```

2021-06-24 05:22 UTC, pablogs9 commented on _posts/2021-04-13-ERF2021.md
> +Then, Jan Staschulat (Bosch) gave an overview of the RCLC API of micro-ROS and highlighted the deterministic RCLC Executor. ([slides](/download/2021-04-13-ERF-bosch.pdf)) Two customers of micro-ROS p
```suggestion
Then, Jan Staschulat (Bosch) gave an overview of the RCLC API of micro-ROS and highlighted the deterministic RCLC Executor. ([slides](/download/2021-04-13-ERF-bosch.pdf)) Two customers of micro-ROS presented their industrial use-cases and emphasized the benefit of micro-ROS: First, Analle Sarazin (WYCA Robotics) presented "Elodie and micro-ROS" ([slides](/download/2021-04-13-ERF-wyca.pdf)) and, secondly, Tomasz Rokosz (Hydra System) presented "micro-ROS enabled GNSS receiver" ([slides](/download/2021-04-13-ERF-hydra.pdf)) ([video of the demo](https://www.youtube.com/watch?v=hTEnTju1Qkg))
```

2021-06-24 05:22 UTC, pablogs9 commented on _posts/2021-04-13-ERF2021.md
> +Finally, we hosted a panel discussion with Pablo Garrido Sanchez (eProsima), Alexandre Malki (PIAP), Jan Staschulat (Bosch), Ana&euml;lle Sarazin (WYCA Robotics) and Tomasz Rokosz (Hydra System) whic
```suggestion
Finally, we hosted a panel discussion with Pablo Garrido Sanchez (eProsima), Alexandre Malki (PIAP), Jan Staschulat (Bosch), Anaelle Sarazin (WYCA Robotics) and Tomasz Rokosz (Hydra System) which stimulated a very lively participation of the audience.
```

2021-06-24 05:32 UTC, pablogs9 commented
I have just updated the URL to a more representative FreeRTOS + POSIX webpage

2021-06-24 05:36 UTC, pablogs9 submitted a review, later dismissed

2021-06-24 06:07 UTC, ralph-lange requested changes
Please embed the slides and videos directly in the post:
* Slides can be embedded with `<embed src="/download/thefilename.pdf" type="application/pdf" width="100%" height="450px"/>`, see https://github.com/micro-ROS/micro-ROS.github.io/blame/master/_posts/2020-03-03-micro-ROS-at-ERF2020.md#L16.
* The Share button at YouTube allows getting the HTML snippet to embed the video.

2021-06-24 06:07 UTC, ralph-lange commented on _posts/2021-04-13-ERF2021.md
> +In this workshop, Francesca Finoccharo (eProsima) presented in detail the micro-ROS architecture, supported platforms and reported recent developments and features: A versatile API for custom transpo
You may even remove the "In this workshop" now, given may proposed addition to the very first sentence.

2021-06-24 06:50 UTC, JanStaschulat commented
> Please embed the slides and videos directly in the post:
> 
>     * Slides can be embedded with `<embed src="/download/thefilename.pdf" type="application/pdf" width="100%" height="450px"/>`, see https://github.com/micro-ROS/micro-ROS.github.io/blame/master/_posts/2020-03-03-micro-ROS-at-ERF2020.md#L16.
> 
>     * The Share button at YouTube allows getting the HTML snippet to embed the video.

thanks for the feedback. It is updated in commit https://github.com/micro-ROS/micro-ROS.github.io/pull/318/commits/48d58df17f11fb310c1353ed7475e6fd8101e632

2021-06-24 06:54 UTC, ralph-lange commented on _posts/2021-04-13-ERF2021.md
> +Video of the demo by Hydra Systems:
```suggestion
Video of the demo by Hydra System:
```

2021-06-24 06:54 UTC, ralph-lange commented on _posts/2021-04-13-ERF2021.md
> +and, secondly, Tomasz Rokosz (Hydra System) presented "micro-ROS enabled GNSS receiver":
```suggestion
And, secondly, Tomasz Rokosz (Hydra System) presented "micro-ROS enabled GNSS receiver":
```

2021-06-24 07:16 UTC, ralph-lange approved these changes

2021-06-24 07:19 UTC, JanStaschulat commented
I updated the blog post accordingly. However, I am not authorized to merge this pull request. @pablogs9 or @ralph-lange, could you merge it?

2021-06-24 07:20 UTC, merged