Concepts: Executor description update
micro-ROS/micro-ROS.github.io pull request #356
Opened 2021-12-14 14:41 UTC by JanStaschulat

2021-12-15 15:11 UTC, pablogs9 submitted a review, later dismissed

2021-12-15 15:33 UTC, ralph-lange commented
I propose to remove the plans/promises for a real-time executor for rclcpp in the introduction since we finally focused on the C client library for micro-ROS only. Instead, the work on the Callback-group Level Executor (and the contributions to the StaticSingleThreadedExecutor ?) could be described/argued at the end of the page as "beyond advanced execution management mechanisms for micro-ROS, we also contributed to improving and extending the Executor concept in rclcpp for standard ROS 2 ..."

What do you think?

In general, the introduction is very long and somehow preempts Sections 2 and 3, i.e., the analyses of the rclcpp standard Executor and typical processing patterns.

2021-12-16 10:20 UTC, JanStaschulat commented
@ralph-lange thanks for your review. I updated the text and added a section about the multi-threaded executor.

2021-12-16 10:30 UTC, ralph-lange commented
Thank you for the updates, @JanStaschulat. I didn't get all the way through your changes yesterday and I'm now proceeding with the review.

2021-12-16 10:56 UTC, ralph-lange requested changes

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
> +* [S2021]<a name="S2021"></a> J. Staschulat, "Micro-ROS: The rclc Executor", ROS 2 Executor: How to make it efficient, real-time and deterministic?, ROS World, Oct. 2021, [[slides](https://ec2a4d36-b
```suggestion
* [S2021]<a name="S2021"></a> J. Staschulat, "Micro-ROS: The rclc Executor", in Workshop ROS 2 Executor: How to make it efficient, real-time and deterministic? at ROS World, Oct. 2021, [[slides](https://ec2a4d36-bac8-4759-b25e-bb1f794177f4.filesusr.com/ugd/984e93_749e27b917a54b45b9ccb5be930841b8.pdf)] [[recorded presentation](https://www.youtube.com/embed/IazrPF3RN1U)]
```

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
>  Therefore the goal of the Real-Time Executor is to support roboticists with practical and easy-to-use real-time mechanisms which provide solutions for:
```suggestion
Therefore the goal of the Executor in micro-ROS is to support roboticists with practical and easy-to-use real-time mechanisms which provide solutions for:
```

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
> +Our approach is to provide a Real-Time Executor on the rcl-layer (as described in section [Introduction to Client Library](../).) in C programming language .
```suggestion
Our approach is to provide a real-time-capable Executor for the rcl+rclc layer (as described in section [Introduction to Client Library](../).) in the C programming language .
```

I would avoid the term "Real-Time Executor" here. This term was used in the work plan of the EU project behind micro-ROS, but in the micro-ROS stack itself, we always use the term "rclc Executor". Therefore, I would write "real-time-capable Executor" or similar.

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
> +While periodic activation is possible in ROS2 by using timers, preemptive scheduling is supported by the operating system and assigning priorities on the granularity of threads/processes that corresp
```suggestion
While periodic activation is possible in ROS 2 by using timers, preemptive scheduling is supported by the operating system and assigning priorities on the granularity of threads/processes that correspond to the ROS nodes; it is not possible to sequentially execute callbacks, which have no data-dependency. Furthermore data is read from the DDS queue just before the callback is executed and data is written sometime during the time the application is executed. While the `spin_period` function of the rclcpp Executor allows to check for data at a fixed period and executing those callbacks for which data is available, however, with this spin-function does not execute all callbacks irrespective wheter data is available or not. So `spin_period` is not helpful to periodically execute a number of callbacks (aka tasks within a process). So we need a mechanism that triggers the execution of multiple callbacks (aka tasks) based on a timer. Data transmission is achieved via DDS which does not allow to implement a LET-semantics. To summarize, we derive the following requirements:
```

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
> +Currently, such a processing order cannot be defined with the default ROS2 Executor. One could in principle design a data-driven pipeline, however if e.g. the Laser scan is needed by some other callb
```suggestion
Currently, such a processing order cannot be defined with the default Executor of rclcpp. One could in principle design a data-driven pipeline, however if e.g. the Laser scan is needed by some other callback in the sense-phase as well as in the plan-phase, the processing order of these subscribers is arbitrary.
```

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
>  In ROS 2, this is currently not possible to be modeled because of the lack of a trigger concept in the ROS2 Executor. Message filters could be used to synchronize input data based on the timestamp in
```suggestion
In ROS 2, this is currently not possible to be modeled because of the lack of a trigger concept in the Executors of rclcpp and rclpy. Message filters could be used to synchronize input data based on the timestamp in the header, but this is only available in rclcpp (and not in rcl). Further more, it would be more efficient to have such a trigger concept directly in the Executor.
```

2021-12-16 10:56 UTC, ralph-lange commented on _docs/concepts/client_library/execution_management/index.md
> +**Derived requirements:**
Previous sentence already ends with a colon.

2021-12-16 11:55 UTC, JanStaschulat commented on _docs/concepts/client_library/execution_management/index.md
> +* [S2021]<a name="S2021"></a> J. Staschulat, "Micro-ROS: The rclc Executor", ROS 2 Executor: How to make it efficient, real-time and deterministic?, ROS World, Oct. 2021, [[slides](https://ec2a4d36-b
done.

2021-12-16 11:59 UTC, JanStaschulat commented on _docs/concepts/client_library/execution_management/index.md
> +**Derived requirements:**
done

2021-12-16 12:03 UTC, JanStaschulat commented
updated the description.

2021-12-16 16:24 UTC, JanStaschulat commented
@ralph-lange the link for cbg_executor_demo is broken 
https://github.com/boschresearch/ros2_demos/tree/cbg_executor_demo/cbg_executor_demo

Where is the repo?

2021-12-16 16:33 UTC, ralph-lange commented
> @ralph-lange the link for cbg_executor_demo is broken https://github.com/boschresearch/ros2_demos/tree/cbg_executor_demo/cbg_executor_demo
> 
> Where is the repo?

It's here now: https://github.com/ros2/examples/tree/master/rclcpp/executors/cbg_executor

2021-12-16 16:42 UTC, JanStaschulat commented
@ralph-lange 
all the links in the section cbg_executor API change to the source code of the cbg_executor (github/boschresearch) are also invalid.

Shall I remove the links or do you want to look for them in the ros2 repository?

2021-12-16 17:12 UTC, JanStaschulat commented
> @ralph-lange all the links in the section cbg_executor API change to the source code of the cbg_executor (github/boschresearch) are also invalid.
> 
> Shall I remove the links or do you want to look for them in the ros2 repository PR https://github.com/ros2/rclcpp/pull/1218/files?authenticity_token=9tvMNjWcL%2BQODfdvxL7NwUKnJIJNTGl3HebJixEnHQHyspazmJEEJHO0trpHiOno5pnLNvYpfz6DSwmRQh8bgQ%3D%3D&file-filters%5B%5D=.cpp ?

Done.

2021-12-16 17:13 UTC, ralph-lange commented
Yes, please remove the Callback-group-level Executor API description. I'll update this section later.

2021-12-16 17:15 UTC, JanStaschulat commented
Then I have finished updating this page. If everything is fine for you, please approve and merge.

2021-12-16 17:16 UTC, JanStaschulat commented
@ralph-lange @pablogs9 . I have finalized updating this page. If everything is fine for you, please approve and merge.

2021-12-16 17:17 UTC, ralph-lange approved these changes
LGTM

2021-12-16 17:17 UTC, merged