Update foxy to humble
micro-ROS/micro-ROS.github.io pull request #401
Opened 2023-03-03 16:06 UTC by Ryanf55

I tried to update the docs to refer to humble. That said, I had some really nasty errors trying to get bundle set up. 

- [ ]  What do we do about [thumper](https://github.com/micro-ROS/micro-ROS_thumper_demo) last being updated for foxy?
- [ ] Does someone else need to run jekyll on this branch for me?

2023-03-03 17:27 UTC, Ryanf55 commented
So I also tried updating the dockerfile to use 22.04, which opened a can of worms. 

First, there was a problem generating docs with the default version of ruby 3, which apparently is incompatible. 
https://talk.jekyllrb.com/t/error-no-implicit-conversion-of-hash-into-integer/5890

According to [github pages](https://pages.github.com/versions/), it's using jekyll 3.9.3, but it's unclear if that supports ruby 3, which might not be true. 

A related issue is here, which may be the actual root cause. 
https://github.com/jekyll/jekyll/issues/9289

Upon further research, 
So, I am updating the dockerfile to use `rbenv` to install 2.7. When trying to clone, I get server cert verification failed. 
This [answer](https://stackoverflow.com/a/69394518/11032285) fixed it (expiring certs). 
``` #0 45.72 fatal: unable to access 'https://github.com/rbenv/rbenv.git/': server certificate verification failed. CAfile: none CRLfile: none ```

Rather than fix this, I found a ruby installer that worked, as long as git was pre-installed. 
So, on commit cf3f8d295e22f324d8712f30ab25d7fb6a62cc8a, it can generate on 22.04.

2023-03-06 06:40 UTC, pablogs9 requested changes

2023-03-06 06:40 UTC, pablogs9 commented on .github/workflows/generate_api_reference.yml
> +            git clone -b master https://github.com/eProsima/Micro-CDR src/Micro-CDR
```suggestion
            git clone -b ros2 https://github.com/eProsima/Micro-CDR src/Micro-CDR
```

2023-03-06 06:40 UTC, pablogs9 commented on .github/workflows/generate_api_reference.yml
> +            git clone -b master https://github.com/eProsima/Micro-XRCE-DDS-Client src/Micro-XRCE-DDS-Client
```suggestion
            git clone -b ros2 https://github.com/eProsima/Micro-XRCE-DDS-Client src/Micro-XRCE-DDS-Client
```

2023-03-06 06:40 UTC, pablogs9 commented on README.md
> +git clone --recurse-submodules <your fork of micro-ROS.github.io>
```suggestion
git clone --recurse-submodules https://github.com/micro-ROS/micro-ROS.github.io
```

2023-03-06 06:40 UTC, pablogs9 commented on README.md
> +When complete, click the link to vuew the local website.
```suggestion
When complete, click the link to view the local website.
```

2023-05-11 05:25 UTC, Ryanf55 commented
Hey there can I get a review/approval? I'd like to also support Iron; this needs to go in first.

2023-05-11 05:34 UTC, pablogs9 commented
I'm not able to build de devcontainer:

```
➜  .devcontainer git:(humble) docker build . -t microros-github-io                                                                                                                                                                                                                                                  
[+] Building 42.0s (6/7)                                                                                                                                                                                                                                                                                            
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                              0.0s 
 => => transferring context: 2B                                                                                                                                                                                                                                                                                0.0s 
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                           0.1s 
 => => transferring dockerfile: 1.45kB                                                                                                                                                                                                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                                                                                                                                                0.0s 
 => [1/4] FROM docker.io/library/ubuntu:22.04                                                                                                                                                                                                                                                                  0.0s 
 => CACHED [2/4] WORKDIR /workspace                                                                                                                                                                                                                                                                            0.0s 
 => ERROR [3/4] RUN apt-get update && apt-get -y upgrade    && apt-get -y install --reinstall ca-certificates    && update-ca-certificates    && apt-get -y install --no-install-recommends build-essential locales zlib1g-dev curl git    && curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/b  42.0s 
------                                                                                                                                                                                                                                                                                                              
 > [3/4] RUN apt-get update && apt-get -y upgrade    && apt-get -y install --reinstall ca-certificates    && update-ca-certificates    && apt-get -y install --no-install-recommends build-essential locales zlib1g-dev curl git    && curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-instal
ler | bash    && echo 'eval "$(~/.rbenv/bin/rbenv init - bash)"' >> ~/.bashrc    && source ~/.bashrc    && rbenv install 2.7.7    && rbenv global 2.7.7    && gem install bundler    && apt-get autoremove -y    && apt-get clean -y    && rm -rf /var/lib/apt/lists/*:                                             
#0 0.298 Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                                                                                                                  
#0 0.446 Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                                                                                                                                                                                            
#0 0.459 Get:3 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [291 kB]                                                                                                                                                                                                                  
#0 0.549 Get:4 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.3 kB]                                                                                                                                                                                                                 
#0 0.552 Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [457 kB]                                                                                                                                                                                                                        
#0 0.587 Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [901 kB]                                                                                                                                                                                                                    
#0 1.015 Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                                                                                                                                                                    
#0 1.151 Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]                                                                                                                                                                                                                                  
#0 1.283 Get:9 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]                                                                                                                                                                                                                            
#0 1.357 Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                                                                                                                                                                                            

[............]

#0 38.86 Setting up gcc-11 (11.3.0-1ubuntu1~22.04) ...
#0 38.90 Setting up g++-11 (11.3.0-1ubuntu1~22.04) ...
#0 38.94 Setting up gcc (4:11.2.0-1ubuntu1) ...
#0 39.00 Setting up dpkg-dev (1.21.1ubuntu2.1) ...
#0 39.07 Setting up liberror-perl (0.17029-1) ...
#0 39.11 Setting up git (1:2.34.1-1ubuntu1.9) ...
#0 39.17 Setting up g++ (4:11.2.0-1ubuntu1) ...
#0 39.20 update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
#0 39.20 update-alternatives: warning: skip creation of /usr/share/man/man1/c++.1.gz because associated file /usr/share/man/man1/g++.1.gz (of link group c++) doesn't exist
#0 39.23 Setting up build-essential (12.9ubuntu3) ...
#0 39.27 Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
#0 39.76 Installing rbenv with git...
#0 39.76 hint: Using 'master' as the name for the initial branch. This default branch  [...]

2023-11-18 02:07 UTC, Ryanf55 commented
Replaced  by #381

2023-11-18 02:07 UTC, closed without merging